version: "3.9"

services:
  fl-server:
    build: ./server
    container_name: fl_server
    ports:
      - "8000:8000"
    networks:
      - flnet

  device:
    build: ./client
    environment:
      - SERVER_ADDRESS=fl-server:8000
    volumes:
      - ./data:/app/data
    depends_on:
      - fl-server
    networks:
      - flnet

networks:
  flnet:
    driver: bridge